import type { ConversionTableEntry } from "./types";

export const table: ConversionTableEntry[] = [
  { from: ["-"], to: "ー", next: [] },
  { from: [","], to: "、", next: [] },
  { from: ["."], to: "。", next: [] },
  { from: ["["], to: "「", next: [] },
  { from: ["]"], to: "」", next: [] },
  { from: ["~"], to: "〜", next: [] },
  { from: ["a"], to: "あ", next: [] },
  { from: ["b", "a"], to: "ば", next: [] },
  { from: ["b", "b"], to: "っ", next: ["b"] },
  { from: ["b", "e"], to: "べ", next: [] },
  { from: ["b", "i"], to: "び", next: [] },
  { from: ["b", "o"], to: "ぼ", next: [] },
  { from: ["b", "u"], to: "ぶ", next: [] },
  { from: ["b", "y", "a"], to: "びゃ", next: [] },
  { from: ["b", "y", "e"], to: "びぇ", next: [] },
  { from: ["b", "y", "i"], to: "びぃ", next: [] },
  { from: ["b", "y", "o"], to: "びょ", next: [] },
  { from: ["b", "y", "u"], to: "びゅ", next: [] },
  { from: ["c", "a"], to: "か", next: [] },
  { from: ["c", "c"], to: "っ", next: ["c"] },
  { from: ["c", "e"], to: "せ", next: [] },
  { from: ["c", "h", "a"], to: "ちゃ", next: [] },
  { from: ["c", "h", "e"], to: "ちぇ", next: [] },
  { from: ["c", "h", "i"], to: "ち", next: [] },
  { from: ["c", "h", "o"], to: "ちょ", next: [] },
  { from: ["c", "h", "u"], to: "ちゅ", next: [] },
  { from: ["c", "i"], to: "し", next: [] },
  { from: ["c", "o"], to: "こ", next: [] },
  { from: ["c", "u"], to: "く", next: [] },
  { from: ["c", "y", "a"], to: "ちゃ", next: [] },
  { from: ["c", "y", "e"], to: "ちぇ", next: [] },
  { from: ["c", "y", "i"], to: "ちぃ", next: [] },
  { from: ["c", "y", "o"], to: "ちょ", next: [] },
  { from: ["c", "y", "u"], to: "ちゅ", next: [] },
  { from: ["d", "'", "i"], to: "でぃ", next: [] },
  { from: ["d", "'", "u"], to: "どぅ", next: [] },
  { from: ["d", "'", "y", "u"], to: "でゅ", next: [] },
  { from: ["d", "a"], to: "だ", next: [] },
  { from: ["d", "d"], to: "っ", next: ["d"] },
  { from: ["d", "e"], to: "で", next: [] },
  { from: ["d", "h", "a"], to: "でゃ", next: [] },
  { from: ["d", "h", "e"], to: "でぇ", next: [] },
  { from: ["d", "h", "i"], to: "でぃ", next: [] },
  { from: ["d", "h", "o"], to: "でょ", next: [] },
  { from: ["d", "h", "u"], to: "でゅ", next: [] },
  { from: ["d", "i"], to: "ぢ", next: [] },
  { from: ["d", "o"], to: "ど", next: [] },
  { from: ["d", "u"], to: "づ", next: [] },
  { from: ["d", "w", "a"], to: "どぁ", next: [] },
  { from: ["d", "w", "e"], to: "どぇ", next: [] },
  { from: ["d", "w", "i"], to: "どぃ", next: [] },
  { from: ["d", "w", "o"], to: "どぉ", next: [] },
  { from: ["d", "w", "u"], to: "どぅ", next: [] },
  { from: ["d", "y", "a"], to: "ぢゃ", next: [] },
  { from: ["d", "y", "e"], to: "ぢぇ", next: [] },
  { from: ["d", "y", "i"], to: "ぢぃ", next: [] },
  { from: ["d", "y", "o"], to: "ぢょ", next: [] },
  { from: ["d", "y", "u"], to: "ぢゅ", next: [] },
  { from: ["e"], to: "え", next: [] },
  { from: ["f", "a"], to: "ふぁ", next: [] },
  { from: ["f", "e"], to: "ふぇ", next: [] },
  { from: ["f", "f"], to: "っ", next: ["f"] },
  { from: ["f", "i"], to: "ふぃ", next: [] },
  { from: ["f", "o"], to: "ふぉ", next: [] },
  { from: ["f", "u"], to: "ふ", next: [] },
  { from: ["f", "u"], to: "ふ", next: [] },
  { from: ["f", "y", "a"], to: "ふゃ", next: [] },
  { from: ["f", "y", "o"], to: "ふょ", next: [] },
  { from: ["f", "y", "u"], to: "ふゅ", next: [] },
  { from: ["g", "a"], to: "が", next: [] },
  { from: ["g", "e"], to: "げ", next: [] },
  { from: ["g", "g"], to: "っ", next: ["g"] },
  { from: ["g", "i"], to: "ぎ", next: [] },
  { from: ["g", "o"], to: "ご", next: [] },
  { from: ["g", "u"], to: "ぐ", next: [] },
  { from: ["g", "w", "a"], to: "ぐぁ", next: [] },
  { from: ["g", "w", "e"], to: "ぐぇ", next: [] },
  { from: ["g", "w", "i"], to: "ぐぃ", next: [] },
  { from: ["g", "w", "o"], to: "ぐぉ", next: [] },
  { from: ["g", "w", "u"], to: "ぐぅ", next: [] },
  { from: ["g", "y", "a"], to: "ぎゃ", next: [] },
  { from: ["g", "y", "e"], to: "ぎぇ", next: [] },
  { from: ["g", "y", "i"], to: "ぎぃ", next: [] },
  { from: ["g", "y", "o"], to: "ぎょ", next: [] },
  { from: ["g", "y", "u"], to: "ぎゅ", next: [] },
  { from: ["h", "a"], to: "は", next: [] },
  { from: ["h", "e"], to: "へ", next: [] },
  { from: ["h", "h"], to: "っ", next: ["h"] },
  { from: ["h", "i"], to: "ひ", next: [] },
  { from: ["h", "o"], to: "ほ", next: [] },
  { from: ["h", "u"], to: "ふ", next: [] },
  { from: ["h", "w", "a"], to: "ふぁ", next: [] },
  { from: ["h", "w", "e"], to: "ふぇ", next: [] },
  { from: ["h", "w", "i"], to: "ふぃ", next: [] },
  { from: ["h", "w", "o"], to: "ふぉ", next: [] },
  { from: ["h", "w", "y", "u"], to: "ふゅ", next: [] },
  { from: ["h", "y", "a"], to: "ひゃ", next: [] },
  { from: ["h", "y", "e"], to: "ひぇ", next: [] },
  { from: ["h", "y", "i"], to: "ひぃ", next: [] },
  { from: ["h", "y", "o"], to: "ひょ", next: [] },
  { from: ["h", "y", "u"], to: "ひゅ", next: [] },
  { from: ["i"], to: "い", next: [] },
  { from: ["j", "a"], to: "じゃ", next: [] },
  { from: ["j", "e"], to: "じぇ", next: [] },
  { from: ["j", "i"], to: "じ", next: [] },
  { from: ["j", "j"], to: "っ", next: ["j"] },
  { from: ["j", "o"], to: "じょ", next: [] },
  { from: ["j", "u"], to: "じゅ", next: [] },
  { from: ["j", "y", "a"], to: "じゃ", next: [] },
  { from: ["j", "y", "e"], to: "じぇ", next: [] },
  { from: ["j", "y", "i"], to: "じぃ", next: [] },
  { from: ["j", "y", "o"], to: "じょ", next: [] },
  { from: ["j", "y", "u"], to: "じゅ", next: [] },
  { from: ["k", "a"], to: "か", next: [] },
  { from: ["k", "e"], to: "け", next: [] },
  { from: ["k", "i"], to: "き", next: [] },
  { from: ["k", "k"], to: "っ", next: ["k"] },
  { from: ["k", "o"], to: "こ", next: [] },
  { from: ["k", "u"], to: "く", next: [] },
  { from: ["k", "w", "a"], to: "くぁ", next: [] },
  { from: ["k", "w", "e"], to: "くぇ", next: [] },
  { from: ["k", "w", "i"], to: "くぃ", next: [] },
  { from: ["k", "w", "o"], to: "くぉ", next: [] },
  { from: ["k", "w", "u"], to: "くぅ", next: [] },
  { from: ["k", "y", "a"], to: "きゃ", next: [] },
  { from: ["k", "y", "e"], to: "きぇ", next: [] },
  { from: ["k", "y", "i"], to: "きぃ", next: [] },
  { from: ["k", "y", "o"], to: "きょ", next: [] },
  { from: ["k", "y", "u"], to: "きゅ", next: [] },
  { from: ["l", "a"], to: "ぁ", next: [] },
  { from: ["l", "e"], to: "ぇ", next: [] },
  { from: ["l", "i"], to: "ぃ", next: [] },
  { from: ["l", "k", "a"], to: "ヵ", next: [] },
  { from: ["l", "k", "e"], to: "ヶ", next: [] },
  { from: ["l", "l"], to: "っ", next: ["l"] },
  { from: ["l", "o"], to: "ぉ", next: [] },
  { from: ["l", "t", "s", "u"], to: "っ", next: [] },
  { from: ["l", "t", "u"], to: "っ", next: [] },
  { from: ["l", "u"], to: "ぅ", next: [] },
  { from: ["l", "w", "a"], to: "ゎ", next: [] },
  { from: ["l", "y", "a"], to: "ゃ", next: [] },
  { from: ["l", "y", "e"], to: "ぇ", next: [] },
  { from: ["l", "y", "i"], to: "ぃ", next: [] },
  { from: ["l", "y", "o"], to: "ょ", next: [] },
  { from: ["l", "y", "u"], to: "ゅ", next: [] },
  { from: ["m", "a"], to: "ま", next: [] },
  { from: ["m", "e"], to: "め", next: [] },
  { from: ["m", "i"], to: "み", next: [] },
  { from: ["m", "m"], to: "っ", next: ["m"] },
  { from: ["m", "o"], to: "も", next: [] },
  { from: ["m", "u"], to: "む", next: [] },
  { from: ["m", "y", "a"], to: "みゃ", next: [] },
  { from: ["m", "y", "e"], to: "みぇ", next: [] },
  { from: ["m", "y", "i"], to: "みぃ", next: [] },
  { from: ["m", "y", "o"], to: "みょ", next: [] },
  { from: ["m", "y", "u"], to: "みゅ", next: [] },
  { from: ["n", "'"], to: "ん", next: [] },
  { from: ["n", "a"], to: "な", next: [] },
  { from: ["n", "e"], to: "ね", next: [] },
  { from: ["n", "i"], to: "に", next: [] },
  { from: ["n", "n"], to: "ん", next: [] },
  { from: ["n", "o"], to: "の", next: [] },
  { from: ["n", "u"], to: "ぬ", next: [] },
  { from: ["n", "y", "a"], to: "にゃ", next: [] },
  { from: ["n", "y", "e"], to: "にぇ", next: [] },
  { from: ["n", "y", "i"], to: "にぃ", next: [] },
  { from: ["n", "y", "o"], to: "にょ", next: [] },
  { from: ["n", "y", "u"], to: "にゅ", next: [] },
  { from: ["n"], to: "ん", next: [] },
  { from: ["o"], to: "お", next: [] },
  { from: ["p", "a"], to: "ぱ", next: [] },
  { from: ["p", "e"], to: "ぺ", next: [] },
  { from: ["p", "i"], to: "ぴ", next: [] },
  { from: ["p", "o"], to: "ぽ", next: [] },
  { from: ["p", "p"], to: "っ", next: ["p"] },
  { from: ["p", "u"], to: "ぷ", next: [] },
  { from: ["p", "y", "a"], to: "ぴゃ", next: [] },
  { from: ["p", "y", "e"], to: "ぴぇ", next: [] },
  { from: ["p", "y", "i"], to: "ぴぃ", next: [] },
  { from: ["p", "y", "o"], to: "ぴょ", next: [] },
  { from: ["p", "y", "u"], to: "ぴゅ", next: [] },
  { from: ["q", "a"], to: "くぁ", next: [] },
  { from: ["q", "e"], to: "くぇ", next: [] },
  { from: ["q", "i"], to: "くぃ", next: [] },
  { from: ["q", "o"], to: "くぉ", next: [] },
  { from: ["q", "q"], to: "っ", next: ["q"] },
  { from: ["q", "u"], to: "く", next: [] },
  { from: ["r", "a"], to: "ら", next: [] },
  { from: ["r", "e"], to: "れ", next: [] },
  { from: ["r", "i"], to: "り", next: [] },
  { from: ["r", "o"], to: "ろ", next: [] },
  { from: ["r", "r"], to: "っ", next: ["r"] },
  { from: ["r", "u"], to: "る", next: [] },
  { from: ["r", "y", "a"], to: "りゃ", next: [] },
  { from: ["r", "y", "e"], to: "りぇ", next: [] },
  { from: ["r", "y", "i"], to: "りぃ", next: [] },
  { from: ["r", "y", "o"], to: "りょ", next: [] },
  { from: ["r", "y", "u"], to: "りゅ", next: [] },
  { from: ["s", "a"], to: "さ", next: [] },
  { from: ["s", "e"], to: "せ", next: [] },
  { from: ["s", "h", "a"], to: "しゃ", next: [] },
  { from: ["s", "h", "e"], to: "しぇ", next: [] },
  { from: ["s", "h", "i"], to: "し", next: [] },
  { from: ["s", "h", "o"], to: "しょ", next: [] },
  { from: ["s", "h", "u"], to: "しゅ", next: [] },
  { from: ["s", "i"], to: "し", next: [] },
  { from: ["s", "o"], to: "そ", next: [] },
  { from: ["s", "s"], to: "っ", next: ["s"] },
  { from: ["s", "u"], to: "す", next: [] },
  { from: ["s", "w", "a"], to: "すぁ", next: [] },
  { from: ["s", "w", "e"], to: "すぇ", next: [] },
  { from: ["s", "w", "i"], to: "すぃ", next: [] },
  { from: ["s", "w", "o"], to: "すぉ", next: [] },
  { from: ["s", "w", "u"], to: "すぅ", next: [] },
  { from: ["s", "y", "a"], to: "しゃ", next: [] },
  { from: ["s", "y", "e"], to: "しぇ", next: [] },
  { from: ["s", "y", "i"], to: "しぃ", next: [] },
  { from: ["s", "y", "o"], to: "しょ", next: [] },
  { from: ["s", "y", "u"], to: "しゅ", next: [] },
  { from: ["t", "'", "i"], to: "てぃ", next: [] },
  { from: ["t", "'", "u"], to: "とぅ", next: [] },
  { from: ["t", "'", "y", "u"], to: "てゅ", next: [] },
  { from: ["t", "a"], to: "た", next: [] },
  { from: ["t", "e"], to: "て", next: [] },
  { from: ["t", "h", "a"], to: "てゃ", next: [] },
  { from: ["t", "h", "e"], to: "てぇ", next: [] },
  { from: ["t", "h", "i"], to: "てぃ", next: [] },
  { from: ["t", "h", "o"], to: "てょ", next: [] },
  { from: ["t", "h", "u"], to: "てゅ", next: [] },
  { from: ["t", "i"], to: "ち", next: [] },
  { from: ["t", "o"], to: "と", next: [] },
  { from: ["t", "s", "a"], to: "つぁ", next: [] },
  { from: ["t", "s", "e"], to: "つぇ", next: [] },
  { from: ["t", "s", "i"], to: "つぃ", next: [] },
  { from: ["t", "s", "o"], to: "つぉ", next: [] },
  { from: ["t", "s", "u"], to: "つ", next: [] },
  { from: ["t", "t"], to: "っ", next: ["t"] },
  { from: ["t", "u"], to: "つ", next: [] },
  { from: ["t", "w", "a"], to: "とぁ", next: [] },
  { from: ["t", "w", "e"], to: "とぇ", next: [] },
  { from: ["t", "w", "i"], to: "とぃ", next: [] },
  { from: ["t", "w", "o"], to: "とぉ", next: [] },
  { from: ["t", "w", "u"], to: "とぅ", next: [] },
  { from: ["t", "y", "a"], to: "ちゃ", next: [] },
  { from: ["t", "y", "e"], to: "ちぇ", next: [] },
  { from: ["t", "y", "i"], to: "ちぃ", next: [] },
  { from: ["t", "y", "o"], to: "ちょ", next: [] },
  { from: ["t", "y", "u"], to: "ちゅ", next: [] },
  { from: ["u"], to: "う", next: [] },
  { from: ["v", "a"], to: "ゔぁ", next: [] },
  { from: ["v", "e"], to: "ゔぇ", next: [] },
  { from: ["v", "i"], to: "ゔぃ", next: [] },
  { from: ["v", "o"], to: "ゔぉ", next: [] },
  { from: ["v", "u"], to: "ゔ", next: [] },
  { from: ["v", "v"], to: "っ", next: ["v"] },
  { from: ["v", "y", "a"], to: "ゔゃ", next: [] },
  { from: ["v", "y", "e"], to: "ゔぇ", next: [] },
  { from: ["v", "y", "i"], to: "ゔぃ", next: [] },
  { from: ["v", "y", "o"], to: "ゔょ", next: [] },
  { from: ["v", "y", "u"], to: "ゔゅ", next: [] },
  { from: ["w", "a"], to: "わ", next: [] },
  { from: ["w", "e"], to: "うぇ", next: [] },
  { from: ["w", "h", "a"], to: "うぁ", next: [] },
  { from: ["w", "h", "e"], to: "うぇ", next: [] },
  { from: ["w", "h", "i"], to: "うぃ", next: [] },
  { from: ["w", "h", "o"], to: "うぉ", next: [] },
  { from: ["w", "h", "u"], to: "う", next: [] },
  { from: ["w", "i"], to: "うぃ", next: [] },
  { from: ["w", "o"], to: "を", next: [] },
  { from: ["w", "u"], to: "う", next: [] },
  { from: ["w", "w", "w"], to: "w", next: ["w", "w"] },
  { from: ["w", "w"], to: "っ", next: ["w"] },
  { from: ["w", "y", "e"], to: "ゑ", next: [] },
  { from: ["w", "y", "i"], to: "ゐ", next: [] },
  { from: ["x", "a"], to: "ぁ", next: [] },
  { from: ["x", "e"], to: "ぇ", next: [] },
  { from: ["x", "i"], to: "ぃ", next: [] },
  { from: ["x", "k", "a"], to: "ヵ", next: [] },
  { from: ["x", "k", "e"], to: "ヶ", next: [] },
  { from: ["x", "n"], to: "ん", next: [] },
  { from: ["x", "o"], to: "ぉ", next: [] },
  { from: ["x", "t", "s", "u"], to: "っ", next: [] },
  { from: ["x", "t", "u"], to: "っ", next: [] },
  { from: ["x", "u"], to: "ぅ", next: [] },
  { from: ["x", "w", "a"], to: "ゎ", next: [] },
  { from: ["x", "x"], to: "っ", next: ["x"] },
  { from: ["x", "y", "a"], to: "ゃ", next: [] },
  { from: ["x", "y", "e"], to: "ぇ", next: [] },
  { from: ["x", "y", "i"], to: "ぃ", next: [] },
  { from: ["x", "y", "o"], to: "ょ", next: [] },
  { from: ["x", "y", "u"], to: "ゅ", next: [] },
  { from: ["y", "a"], to: "や", next: [] },
  { from: ["y", "e"], to: "いぇ", next: [] },
  { from: ["y", "o"], to: "よ", next: [] },
  { from: ["y", "u"], to: "ゆ", next: [] },
  { from: ["y", "y"], to: "っ", next: ["y"] },
  { from: ["z", "-"], to: "〜", next: [] },
  { from: ["z", ","], to: "‥", next: [] },
  { from: ["z", "."], to: "…", next: [] },
  { from: ["z", "["], to: "『", next: [] },
  { from: ["z", "]"], to: "』", next: [] },
  { from: ["z", "/"], to: "・", next: [] },
  { from: ["z", "a"], to: "ざ", next: [] },
  { from: ["z", "e"], to: "ぜ", next: [] },
  { from: ["z", "h"], to: "←", next: [] },
  { from: ["z", "i"], to: "じ", next: [] },
  { from: ["z", "j"], to: "↓", next: [] },
  { from: ["z", "k"], to: "↑", next: [] },
  { from: ["z", "l"], to: "→", next: [] },
  { from: ["z", "o"], to: "ぞ", next: [] },
  { from: ["z", "u"], to: "ず", next: [] },
  { from: ["z", "w", "a"], to: "ずぁ", next: [] },
  { from: ["z", "w", "e"], to: "ずぇ", next: [] },
  { from: ["z", "w", "i"], to: "ずぃ", next: [] },
  { from: ["z", "w", "o"], to: "ずぉ", next: [] },
  { from: ["z", "w", "u"], to: "ずぅ", next: [] },
  { from: ["z", "y", "a"], to: "じゃ", next: [] },
  { from: ["z", "y", "e"], to: "じぇ", next: [] },
  { from: ["z", "y", "i"], to: "じぃ", next: [] },
  { from: ["z", "y", "o"], to: "じょ", next: [] },
  { from: ["z", "y", "u"], to: "じゅ", next: [] },
  { from: ["z", "z"], to: "っ", next: ["z"] },
];
